/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Models.LoginModel;
import Models.Data.Staff;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nguye
 */
public class Login extends javax.swing.JFrame {
    public static String FullNameStaff;
    public static String Role;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Login");
        setSize(645, 536);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Đặt màu nền cho SignIn JFrame
        getContentPane().setBackground(Color.WHITE); // Sửa màu nền thành màu trắng

        // Set frame ở giữa màn hình
        this.setLocationRelativeTo(null);
        // controller
//        controller = new StaffControllerImp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_UserName = new javax.swing.JTextField();
        lbl__Password = new javax.swing.JTextField();
        btn__Login = new javax.swing.JButton();
        btn__SignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        btn__Login.setLabel("Đăng nhập");
        btn__Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__LoginActionPerformed(evt);
            }
        });
        btn__Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn__LoginKeyPressed(evt);
            }
        });

        btn__SignIn.setText("Đăng ký");
        btn__SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__SignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_UserName)
                                .addComponent(lbl__Password, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn__Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn__SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(lbl_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl__Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn__Login)
                .addGap(18, 18, 18)
                .addComponent(btn__SignIn)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn__LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__LoginActionPerformed
        // TODO add your handling code here:
        String UserName = lbl_UserName.getText();
        String PassWord = lbl__Password.getText();
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        Staff staff = new Staff();
        staff.setEmail(UserName);
        staff.setPasswordHas(PassWord);
        if(loginController.Login(staff)) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Get FullName
            FullNameStaff =  loginController.GetFullNameStaff(UserName, PassWord);
            Role = loginController.getRoleUser(UserName, PassWord);
            staff.setFullName(UserName);
            // Get Role
            
            HomeStaff HomeStaffFrame = new HomeStaff();
            HomeStaffFrame.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn__LoginActionPerformed

    private void btn__SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__SignInActionPerformed
        // TODO add your handling code here:
        SignUp SignUpFrame = new SignUp();
        SignUpFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn__SignInActionPerformed

    private void btn__LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn__LoginKeyPressed
        // TODO add your handling code here:
        String UserName = lbl_UserName.getText();
        String PassWord = lbl__Password.getText();
        LoginModel loginModel = new LoginModel();
        LoginController loginController = new LoginController(loginModel);
        Staff staff = new Staff();
        staff.setEmail(UserName);
        staff.setPasswordHas(PassWord);
        if(loginController.Login(staff)) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            // Get FullName
            FullNameStaff =  loginController.GetFullNameStaff(UserName, PassWord);
            Role = loginController.getRoleUser(UserName, PassWord);
            staff.setFullName(UserName);
            // Get Role
            
            HomeStaff HomeStaffFrame = new HomeStaff();
            HomeStaffFrame.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn__LoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn__Login;
    private javax.swing.JButton btn__SignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lbl_UserName;
    private javax.swing.JTextField lbl__Password;
    // End of variables declaration//GEN-END:variables
}
