/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HrManagerController;
import Models.Data.Staff;
import Models.HRManagerModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class UpdateStaff extends javax.swing.JFrame {
    
    /**
     * Creates new form UpdateStaff
     */
    public UpdateStaff() {
        initComponents();
        int IdStaff = HrManager.IdStaff;
        HRManagerModel hrManagerModel = new HRManagerModel();
        HrManagerController hrManagerController = new HrManagerController(hrManagerModel);
        Staff staff = hrManagerController.GetStaffById(IdStaff);
        txt_Id.setText(String.valueOf(staff.iD));
        lbl__FirstName.setText(staff.firstName);
        lbl__LastName.setText(staff.lastName);
        jDC_DOB.setDate(staff.dob);
        lbl__PhoneNumber.setText(String.valueOf(staff.phoneNumber));
        lbl__UserName1.setText((staff.Email));
        jDC_HireDate.setDate(staff.hireDate);
        lbl__Salary.setText(String.valueOf(staff.salary));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_AddFood1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl__FirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl__LastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbb__Gender = new javax.swing.JComboBox<>();
        jDC_DOB = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        lbl__PhoneNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl__Salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDC_HireDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cbb__Position = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        lbl__UserName1 = new javax.swing.JTextField();
        btn_Save = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jCB_Dismissal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_AddFood1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_AddFood1.setText("Sửa nhân viên");
        getContentPane().add(lbl_AddFood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 155, 69));

        jLabel2.setText("Họ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 66, 20));
        getContentPane().add(lbl__FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 162, -1));

        jLabel3.setText("Tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 37, -1));
        getContentPane().add(lbl__LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 164, -1));

        jLabel4.setText("Ngày sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 63, -1));

        jLabel6.setText("Giới tính");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 63, -1));

        cbb__Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        getContentPane().add(cbb__Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 164, -1));

        jDC_DOB.setDateFormatString("dd MMM, yyyy");
        getContentPane().add(jDC_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 162, -1));

        jLabel5.setText("Số điện thoại");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 103, -1));
        getContentPane().add(lbl__PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 374, -1));

        jLabel12.setText("Email");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 81, -1));
        getContentPane().add(lbl__Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 374, -1));

        jLabel13.setText("Ngày vào làm");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 81, -1));

        jDC_HireDate.setDateFormatString("dd MMM, yyyy");
        getContentPane().add(jDC_HireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 162, -1));

        jLabel7.setText("Chức vụ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 63, -1));

        cbb__Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Thu ngân", "Phục vụ" }));
        getContentPane().add(cbb__Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 158, -1));

        jLabel14.setText("Lương");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 81, -1));
        getContentPane().add(lbl__UserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 374, -1));

        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 75, -1));

        btn_Exit.setText("Thoát");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Mã nhân viên");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, -1));

        txt_Id.setEnabled(false);
        getContentPane().add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 240, -1));

        jCB_Dismissal.setText("Sa thải");
        getContentPane().add(jCB_Dismissal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 85, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        int state = 0;
        if(jCB_Dismissal.isSelected()) {
            state = 1;
        }
        HRManagerModel hRManagerModel = new HRManagerModel();
        HrManagerController hrManagerController = new HrManagerController(hRManagerModel);
        Staff staff = new Staff();
        staff.setiD(HrManager.IdStaff);
        staff.setFirstName(lbl__FirstName.getText());
        staff.setLastName(lbl__LastName.getText());
        Date selectDate = jDC_DOB.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dates = dateFormat.format(selectDate);
        java.sql.Date sqlDate = new java.sql.Date(selectDate.getTime());
        staff.setDob(sqlDate);
        staff.setGender(cbb__Gender.getSelectedItem().toString());
        staff.setPhoneNumber(Integer.parseInt(lbl__PhoneNumber.getText()));
        staff.setEmail(lbl__UserName1.getText());
        Date HireDate = jDC_HireDate.getDate();
        java.sql.Date HireDateSql = new java.sql.Date(HireDate.getTime());
        staff.setHireDate(HireDateSql);
        staff.setPosition(cbb__Position.getSelectedItem().toString());
        staff.setSalary(Double.parseDouble(lbl__Salary.getText()));
        if(hrManagerController.UpdateStaff(staff)) {
            JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            HrManager hrManager = new HrManager();
            hrManager.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        HrManager hrManager = new HrManager();
        hrManager.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Save;
    private javax.swing.JComboBox<String> cbb__Gender;
    private javax.swing.JComboBox<String> cbb__Position;
    private javax.swing.JCheckBox jCB_Dismissal;
    private com.toedter.calendar.JDateChooser jDC_DOB;
    private com.toedter.calendar.JDateChooser jDC_HireDate;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_AddFood1;
    private javax.swing.JTextField lbl__FirstName;
    private javax.swing.JTextField lbl__LastName;
    private javax.swing.JTextField lbl__PhoneNumber;
    private javax.swing.JTextField lbl__Salary;
    private javax.swing.JTextField lbl__UserName1;
    private javax.swing.JTextField txt_Id;
    // End of variables declaration//GEN-END:variables
}
